# fly.toml app configuration file generated for fsoanecdotes on 2024-01-12T14:14:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fsoanecdotes"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  server = "node server"
  app = "npm start"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app", "server"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
